/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddSortOrderUpdateAllOf {
    #[serde(rename = "sort-order")]
    pub sort_order: Box<crate::models::SortOrder>,
}

impl AddSortOrderUpdateAllOf {
    pub fn new(sort_order: crate::models::SortOrder) -> AddSortOrderUpdateAllOf {
        AddSortOrderUpdateAllOf {
            sort_order: Box::new(sort_order),
        }
    }
}
