/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddPartitionSpecUpdateAllOf {
    #[serde(rename = "spec")]
    pub spec: Box<crate::models::PartitionSpec>,
}

impl AddPartitionSpecUpdateAllOf {
    pub fn new(spec: crate::models::PartitionSpec) -> AddPartitionSpecUpdateAllOf {
        AddPartitionSpecUpdateAllOf {
            spec: Box::new(spec),
        }
    }
}
