// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BaseUpdate {
    #[serde(rename = "action")]
    pub action: Action,
}

impl BaseUpdate {
    pub fn new(action: Action) -> BaseUpdate {
        BaseUpdate { action }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "upgrade-format-version")]
    UpgradeFormatVersion,
    #[serde(rename = "add-schema")]
    AddSchema,
    #[serde(rename = "set-current-schema")]
    SetCurrentSchema,
    #[serde(rename = "add-spec")]
    AddSpec,
    #[serde(rename = "set-default-spec")]
    SetDefaultSpec,
    #[serde(rename = "add-sort-order")]
    AddSortOrder,
    #[serde(rename = "set-default-sort-order")]
    SetDefaultSortOrder,
    #[serde(rename = "add-snapshot")]
    AddSnapshot,
    #[serde(rename = "set-snapshot-ref")]
    SetSnapshotRef,
    #[serde(rename = "remove-snapshots")]
    RemoveSnapshots,
    #[serde(rename = "remove-snapshot-ref")]
    RemoveSnapshotRef,
    #[serde(rename = "set-location")]
    SetLocation,
    #[serde(rename = "set-properties")]
    SetProperties,
    #[serde(rename = "remove-properties")]
    RemoveProperties,
}

impl Default for Action {
    fn default() -> Action {
        Self::UpgradeFormatVersion
    }
}
