/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Expression {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "left")]
    pub left: Box<crate::models::Expression>,
    #[serde(rename = "right")]
    pub right: Box<crate::models::Expression>,
    #[serde(rename = "child")]
    pub child: Box<crate::models::Expression>,
    #[serde(rename = "term")]
    pub term: Box<crate::models::Term>,
    #[serde(rename = "values")]
    pub values: Vec<serde_json::Value>,
    #[serde(rename = "value")]
    pub value: serde_json::Value,
}

impl Expression {
    pub fn new(
        r#type: String,
        left: crate::models::Expression,
        right: crate::models::Expression,
        child: crate::models::Expression,
        term: crate::models::Term,
        values: Vec<serde_json::Value>,
        value: serde_json::Value,
    ) -> Expression {
        Expression {
            r#type,
            left: Box::new(left),
            right: Box::new(right),
            child: Box::new(child),
            term: Box::new(term),
            values,
            value,
        }
    }
}
