/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetadataLogInner {
    #[serde(rename = "metadata-file")]
    pub metadata_file: String,
    #[serde(rename = "timestamp-ms")]
    pub timestamp_ms: i64,
}

impl MetadataLogInner {
    pub fn new(metadata_file: String, timestamp_ms: i64) -> MetadataLogInner {
        MetadataLogInner {
            metadata_file,
            timestamp_ms,
        }
    }
}
