/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NotExpression {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "child")]
    pub child: Box<crate::models::Expression>,
}

impl NotExpression {
    pub fn new(r#type: String, child: crate::models::Expression) -> NotExpression {
        NotExpression {
            r#type,
            child: Box::new(child),
        }
    }
}
