/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NullOrder {
    #[serde(rename = "nulls-first")]
    First,
    #[serde(rename = "nulls-last")]
    Last,
}

impl ToString for NullOrder {
    fn to_string(&self) -> String {
        match self {
            Self::First => String::from("nulls-first"),
            Self::Last => String::from("nulls-last"),
        }
    }
}

impl Default for NullOrder {
    fn default() -> NullOrder {
        Self::First
    }
}
