/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SetExpression {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "term")]
    pub term: Box<crate::models::Term>,
    #[serde(rename = "values")]
    pub values: Vec<serde_json::Value>,
}

impl SetExpression {
    pub fn new(
        r#type: String,
        term: crate::models::Term,
        values: Vec<serde_json::Value>,
    ) -> SetExpression {
        SetExpression {
            r#type,
            term: Box::new(term),
            values,
        }
    }
}
