/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SetSnapshotRefUpdate {
    #[serde(rename = "action")]
    pub action: Action,
    #[serde(rename = "type")]
    pub r#type: RHashType,
    #[serde(rename = "snapshot-id")]
    pub snapshot_id: i64,
    #[serde(rename = "max-ref-age-ms", skip_serializing_if = "Option::is_none")]
    pub max_ref_age_ms: Option<i64>,
    #[serde(
        rename = "max-snapshot-age-ms",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_snapshot_age_ms: Option<i64>,
    #[serde(
        rename = "min-snapshots-to-keep",
        skip_serializing_if = "Option::is_none"
    )]
    pub min_snapshots_to_keep: Option<i32>,
    #[serde(rename = "ref-name")]
    pub ref_name: String,
}

impl SetSnapshotRefUpdate {
    pub fn new(
        action: Action,
        r#type: RHashType,
        snapshot_id: i64,
        ref_name: String,
    ) -> SetSnapshotRefUpdate {
        SetSnapshotRefUpdate {
            action,
            r#type,
            snapshot_id,
            max_ref_age_ms: None,
            max_snapshot_age_ms: None,
            min_snapshots_to_keep: None,
            ref_name,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "upgrade-format-version")]
    UpgradeFormatVersion,
    #[serde(rename = "add-schema")]
    AddSchema,
    #[serde(rename = "set-current-schema")]
    SetCurrentSchema,
    #[serde(rename = "add-spec")]
    AddSpec,
    #[serde(rename = "set-default-spec")]
    SetDefaultSpec,
    #[serde(rename = "add-sort-order")]
    AddSortOrder,
    #[serde(rename = "set-default-sort-order")]
    SetDefaultSortOrder,
    #[serde(rename = "add-snapshot")]
    AddSnapshot,
    #[serde(rename = "set-snapshot-ref")]
    SetSnapshotRef,
    #[serde(rename = "remove-snapshots")]
    RemoveSnapshots,
    #[serde(rename = "remove-snapshot-ref")]
    RemoveSnapshotRef,
    #[serde(rename = "set-location")]
    SetLocation,
    #[serde(rename = "set-properties")]
    SetProperties,
    #[serde(rename = "remove-properties")]
    RemoveProperties,
}

impl Default for Action {
    fn default() -> Action {
        Self::UpgradeFormatVersion
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "tag")]
    Tag,
    #[serde(rename = "branch")]
    Branch,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Tag
    }
}
