/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SetCurrentSchemaUpdateAllOf {
    /// Schema ID to set as current, or -1 to set last added schema
    #[serde(rename = "schema-id")]
    pub schema_id: i32,
}

impl SetCurrentSchemaUpdateAllOf {
    pub fn new(schema_id: i32) -> SetCurrentSchemaUpdateAllOf {
        SetCurrentSchemaUpdateAllOf { schema_id }
    }
}
