/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StructField {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: Box<crate::models::Type>,
    #[serde(rename = "required")]
    pub required: bool,
    #[serde(rename = "doc", skip_serializing_if = "Option::is_none")]
    pub doc: Option<String>,
}

impl StructField {
    pub fn new(id: i32, name: String, r#type: crate::models::Type, required: bool) -> StructField {
        StructField {
            id,
            name,
            r#type: Box::new(r#type),
            required,
            doc: None,
        }
    }
}
