repos:
  - repo: local
    hooks:
    - id: format
      name: format
      language: system
      files: '\.rs$'
      entry: cargo fmt --all
      pass_filenames: false
    - id: clipper
      name: clipper
      language: system
      files: '\.rs$'
      entry: cargo clippy --all-targets --all-features --fix --workspace -- -D warnings
      pass_filenames: false
