// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

use aws_sdk_kms::types::{DataKeySpec, EncryptionAlgorithmSpec};
use iceberg::{Error, ErrorKind, Result};
use iceberg_property_macro::Properties;

/// Catalog property selecting an AWS profile.
pub const AWS_PROFILE_NAME: &str = "profile_name";
/// Catalog property selecting the AWS region.
pub const AWS_REGION_NAME: &str = "region_name";
/// Catalog property containing a static AWS access key ID.
pub const AWS_ACCESS_KEY_ID: &str = "aws_access_key_id";
/// Catalog property containing a static AWS secret access key.
pub const AWS_SECRET_ACCESS_KEY: &str = "aws_secret_access_key";
/// Catalog property containing a static AWS session token.
pub const AWS_SESSION_TOKEN: &str = "aws_session_token";

/// Catalog property overriding the AWS KMS service endpoint.
pub const KMS_ENDPOINT: &str = "kms.endpoint";
/// Catalog property selecting the AWS KMS encryption algorithm.
pub const KMS_ENCRYPTION_ALGORITHM_SPEC: &str = "kms.encryption-algorithm-spec";
/// Default AWS KMS encryption algorithm, matching Iceberg Java.
pub const KMS_ENCRYPTION_ALGORITHM_SPEC_DEFAULT: &str = "SYMMETRIC_DEFAULT";
/// Catalog property selecting the size of keys generated by AWS KMS.
pub const KMS_DATA_KEY_SPEC: &str = "kms.data-key-spec";
/// Default AWS KMS generated key size, matching Iceberg Java.
pub const KMS_DATA_KEY_SPEC_DEFAULT: &str = "AES_256";

#[derive(Clone, Properties)]
pub(crate) struct AwsKmsConfig {
    #[property(key = KMS_ENDPOINT, default = None)]
    pub(crate) endpoint: Option<String>,
    #[property(
        key = KMS_ENCRYPTION_ALGORITHM_SPEC,
        default = KMS_ENCRYPTION_ALGORITHM_SPEC_DEFAULT,
        parse_with = parse_encryption_algorithm
    )]
    pub(crate) encryption_algorithm: EncryptionAlgorithmSpec,
    #[property(
        key = KMS_DATA_KEY_SPEC,
        default = KMS_DATA_KEY_SPEC_DEFAULT,
        parse_with = parse_data_key_spec
    )]
    pub(crate) data_key_spec: DataKeySpec,
}

fn parse_encryption_algorithm(value: &str) -> Result<EncryptionAlgorithmSpec> {
    EncryptionAlgorithmSpec::try_parse(value).map_err(|source| {
        Error::new(
            ErrorKind::DataInvalid,
            format!("Unsupported AWS KMS encryption algorithm: {value}"),
        )
        .with_source(source)
    })
}

fn parse_data_key_spec(value: &str) -> Result<DataKeySpec> {
    DataKeySpec::try_parse(value).map_err(|source| {
        Error::new(
            ErrorKind::DataInvalid,
            format!("Unsupported AWS KMS data key spec: {value}"),
        )
        .with_source(source)
    })
}

#[cfg(test)]
mod tests {
    use std::collections::HashMap;

    use super::*;

    #[test]
    fn test_defaults_match_iceberg_java() {
        let config = AwsKmsConfig::from_properties(&HashMap::new()).unwrap();

        assert_eq!(
            config.encryption_algorithm,
            EncryptionAlgorithmSpec::SymmetricDefault
        );
        assert_eq!(config.data_key_spec, DataKeySpec::Aes256);
        assert_eq!(config.endpoint, None);
    }

    #[test]
    fn test_parse_overrides() {
        let properties = HashMap::from([
            (
                KMS_ENDPOINT.to_string(),
                "http://localhost:4566".to_string(),
            ),
            (
                KMS_ENCRYPTION_ALGORITHM_SPEC.to_string(),
                "RSAES_OAEP_SHA_256".to_string(),
            ),
            (KMS_DATA_KEY_SPEC.to_string(), "AES_128".to_string()),
        ]);

        let config = AwsKmsConfig::from_properties(&properties).unwrap();
        assert_eq!(config.endpoint.as_deref(), Some("http://localhost:4566"));
        assert_eq!(
            config.encryption_algorithm,
            EncryptionAlgorithmSpec::RsaesOaepSha256
        );
        assert_eq!(config.data_key_spec, DataKeySpec::Aes128);
    }

    #[test]
    fn test_reject_unknown_values() {
        let bad_algorithm = HashMap::from([(
            KMS_ENCRYPTION_ALGORITHM_SPEC.to_string(),
            "unknown".to_string(),
        )]);
        let Err(error) = AwsKmsConfig::from_properties(&bad_algorithm) else {
            panic!("unknown encryption algorithms must be rejected");
        };
        assert_eq!(error.kind(), ErrorKind::DataInvalid);

        let bad_key_spec = HashMap::from([(KMS_DATA_KEY_SPEC.to_string(), "AES_192".to_string())]);
        let Err(error) = AwsKmsConfig::from_properties(&bad_key_spec) else {
            panic!("unknown data-key specifications must be rejected");
        };
        assert_eq!(error.kind(), ErrorKind::DataInvalid);
    }
}
