// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! AWS Key Management Service integration.
//!
//! This module provides [`AwsKmsClientFactory`],
//! which creates AWS-backed implementations of Iceberg's
//! [`KeyManagementClient`](iceberg::encryption::KeyManagementClient). The factory can
//! be supplied to any Iceberg catalog builder through
//! [`CatalogBuilder::with_kms_client_factory`](iceberg::CatalogBuilder::with_kms_client_factory).
//!
//! # Permissions
//!
//! The KMS key referenced by a table's `encryption.key-id` property requires
//! `kms:Decrypt` for reads. Writes with `SYMMETRIC_DEFAULT` use
//! `kms:GenerateDataKey`. Writes with an asymmetric encryption algorithm
//! generate the key-encryption key locally and require `kms:Encrypt` to wrap it.
//!
//! Iceberg Java always generates key-encryption keys locally and wraps them
//! with `kms:Encrypt`, so key policies written for Java writers must also grant
//! `kms:GenerateDataKey` to Rust writers using `SYMMETRIC_DEFAULT`. Tables
//! written by either implementation are readable by the other.
//!
//! # Configuration
//!
//! The factory reads the catalog properties supplied by the application when
//! the catalog is constructed. Configuration returned later by a REST catalog
//! server is not currently available when the KMS client is created.
//!
//! These KMS properties match Iceberg Java:
//!
//! - `kms.endpoint` overrides the KMS service endpoint. It must be an `http` or
//!   `https` URL.
//! - `kms.encryption-algorithm-spec` selects the KMS encryption algorithm and
//!   defaults to `SYMMETRIC_DEFAULT`.
//! - `kms.data-key-spec` selects the size of key-encryption keys generated by
//!   KMS and defaults to `AES_256`. It only applies to `SYMMETRIC_DEFAULT`;
//!   with an asymmetric algorithm, locally generated key-encryption keys are
//!   sized by the table property `encryption.data-key-length`, like data keys.
//!
//! Unless an [`SdkConfig`](aws_config::SdkConfig) is supplied through
//! [`AwsKmsClientFactory::with_sdk_config`], in which case they are not read,
//! the AWS SDK's default credential and region provider chains are used, and
//! these properties override them:
//!
//! - `client.region` selects the region, as in Iceberg Java. The `region_name`
//!   property used by the Glue and S3 Tables catalogs is also accepted, with
//!   lower precedence.
//! - `profile_name` selects a profile from the shared AWS configuration files.
//! - `aws_access_key_id`, `aws_secret_access_key`, and the optional
//!   `aws_session_token` provide static credentials.
//!
//! Assuming an IAM role through `client.assume-role.*` is not supported yet:
//! catalog properties that set `client.assume-role.arn` are rejected, rather
//! than having the KMS client use a different identity than the catalog's S3
//! file IO. Supply an [`SdkConfig`](aws_config::SdkConfig) with the desired
//! credentials instead.
//!
//! `client.credentials-provider` and `client.factory` name Java classes and
//! are ignored, as are the `s3.*` credentials used by S3 file IO.
//!
//! # Security considerations
//!
//! With an asymmetric encryption algorithm, wrapping a key-encryption key only
//! requires the KMS public key. Anyone who can write table metadata can
//! therefore add a key-encryption key they know, without any KMS permissions;
//! `SYMMETRIC_DEFAULT` requires `kms:GenerateDataKey` or `kms:Encrypt` instead.
//!
//! With an asymmetric encryption algorithm, plaintext key-encryption keys are
//! sent to KMS, and the AWS SDK's `TRACE` logs include request bodies.
//!
//! # Example
//!
//! ```rust,no_run
//! use std::collections::HashMap;
//! use std::sync::Arc;
//!
//! use iceberg::CatalogBuilder;
//! use iceberg::io::CLIENT_REGION;
//! use iceberg::memory::{MEMORY_CATALOG_WAREHOUSE, MemoryCatalogBuilder};
//! use iceberg_kms::aws::AwsKmsClientFactory;
//!
//! # async fn example() -> iceberg::Result<()> {
//! let properties = HashMap::from([
//!     (
//!         MEMORY_CATALOG_WAREHOUSE.to_string(),
//!         "s3://bucket/warehouse".to_string(),
//!     ),
//!     (CLIENT_REGION.to_string(), "eu-west-2".to_string()),
//! ]);
//! // Any catalog builder accepts a KMS client factory. A storage factory for
//! // the warehouse is omitted for brevity.
//! let catalog = MemoryCatalogBuilder::default()
//!     .with_kms_client_factory(Arc::new(AwsKmsClientFactory::new()))
//!     .load("catalog", properties)
//!     .await?;
//! # let _ = catalog;
//! # Ok(())
//! # }
//! ```

mod client;
mod config;
mod factory;

pub use config::{
    KMS_DATA_KEY_SPEC, KMS_DATA_KEY_SPEC_DEFAULT, KMS_ENCRYPTION_ALGORITHM_SPEC,
    KMS_ENCRYPTION_ALGORITHM_SPEC_DEFAULT, KMS_ENDPOINT,
};
pub use factory::AwsKmsClientFactory;
