[book]
authors = ["Iceberg Community"]
language = "en"
multilingual = false
src = "src"
title = "Iceberg Rust"

[output.html]
git-repository-url = "https://github.com/apache/iceberg-rust"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/apache/iceberg-rust/edit/main/website/{path}"
cname = "rust.iceberg.opendal.org"
