#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: "Issue and Pull Request Labeler"
on:
  issues:
    types: [opened, edited]
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types: [opened, edited]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  triage:
    if: github.repository_owner == 'apache'
    runs-on: ubuntu-slim
    steps:
    - uses: github/issue-labeler@ccca1e16fcb66762200e616fc29b57b940c1cb67 # v3.5
      with:
        configuration-path: .github/labeler.yml  # label -> regex rules
        enable-versioned-regex: 0  # required; 0 = no versioned configs
        include-title: 1  # match title
        include-body: 1  # match body (default)
